<a href="https://colab.research.google.com/github/CintiaYYS/AnalisesColab/blob/main/Alfabetizacao_BR_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook destinado a estudo de Python e análise de dados.

Alfabetização no Brasil

* Raça
* Gênero
* Faixa etária

A base de dados utilizada neste estudo foi extraída do site https://basedosdados.org/search

In [1]:
import pandas as pd

# Importando a base de dados que está disponível no repositório local
ibge_dataset = pd.read_csv("br_ibge_censo_2022_alfabetizacao_grupo_idade_sexo_raca.csv")

#Visualizando as informações básicas da base de dados
ibge_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 779800 entries, 0 to 779799
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_municipio   779800 non-null  int64
 1   cor_raca       779800 non-null  object
 2   sexo           779800 non-null  object
 3   grupo_idade    779800 non-null  object
 4   alfabetizacao  779800 non-null  object
 5   populacao      529715 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 35.7+ MB

## Analisando cada coluna e entendendo os valores

id_municipio, cor_raca, sexo,    grupo_idade, alfabetizacao, populacao

### id_municipio

In [2]:
ids_municipios = ibge_dataset["id_municipio"].unique()
print(ids_municipios)

[1100023 1100262 1101005 ... 3509502 5300108 3550308]

In [7]:
len(ids_municipios)

5570

#### Relacionando o id_municipio com a região

Para relacionar o município com uma das regiões do Brasil, é preciso usar a base de dados que relacionada aos municípios do Brasil.

Assim, ao final desta etapa, cada município deve ter uma região associada a ele.

In [4]:
municipios = pd.read_csv("br_bd_diretorios_brasil_municipios.csv")
municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_municipio               5571 non-null   int64
 1   id_municipio_6             5571 non-null   int64
 2   id_municipio_tse           5570 non-null   float64
 3   id_municipio_rf            5570 non-null   float64
 4   id_municipio_bcb           5570 non-null   float64
 5   nome                       5571 non-null   object
 6   capital_uf                 5570 non-null   float64
 7   id_comarca                 5570 non-null   float64
 8   id_regiao_saude            5570 non-null   float64
 9   nome_regiao_saude          5570 non-null   object
 10  id_regiao_imediata         5571 non-null   int64
 11  nome_regiao_imediata       5571 non-null   object
 12  id_regiao_intermediaria    5571 non-null   int64
 13  nome_regiao_intermediaria  5571 non-null   object
 14  id_microrregiao            5570 non-null   float64
 15  nome_microrregiao          5570 non-null   object
 16  id_mesorregiao             5570 non-null   float64
 17  nome_mesorregiao           5570 non-null   object
 18  id_regiao_metropolitana    1432 non-null   object
 19  nome_regiao_metropolitana  1432 non-null   object
 20  ddd                        5570 non-null   float64
 21  id_uf                      5571 non-null   int64
 22  sigla_uf                   5571 non-null   object
 23  nome_uf                    5571 non-null   object
 24  nome_regiao                5571 non-null   object
 25  amazonia_legal             5571 non-null   int64
 26  centroide                  5571 non-null   object
dtypes: float64(9), int64(6), object(12)
memory usage: 1.1+ MB

In [5]:
# Verificando os id_municipio e nome_regiao
municipios[["id_municipio", "nome_regiao"]]

      id_municipio   nome_regiao
0          5101837  Centro-Oeste
1          1100809         Norte
2          1100338         Norte
3          1100205         Norte
4          1101104         Norte
...            ...           ...
5566       5209150  Centro-Oeste
5567       5220405  Centro-Oeste
5568       5216304  Centro-Oeste
5569       5218508  Centro-Oeste
5570       5300108  Centro-Oeste

[5571 rows x 2 columns]

### Adicionando a região à base de dados ibge

In [6]:
#Adicionando a região de acordo com o id_municipio
ibge_dataset = ibge_dataset.merge(municipios[["id_municipio", "nome_regiao"]], on="id_municipio")
ibge_dataset.head(9)

,id_municipio,cor_raca,sexo,grupo_idade,alfabetizacao,populacao,nome_regiao
0,1100023,Indígena,Homens,15 a 19 anos,Não alfabetizadas,NaN,Norte
1,1100262,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
2,1101005,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
3,1101435,Amarela,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
4,1101435,Indígena,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
5,1100346,Indígena,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
6,1100015,Amarela,Homens,15 a 19 anos,Não alfabetizadas,NaN,Norte
7,1100031,Preta,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte
8,1101468,Indígena,Mulheres,15 a 19 anos,Não alfabetizadas,NaN,Norte

In [10]:
# Verificando os registros cuja coluna populacao é NaN
populacao_NaN = ibge_dataset[ibge_dataset["populacao"].isna()]
populacao_NaN["id_municipio"]
len(populacao_NaN)

250085

In [14]:
#Verificando quantos registros não são NaN em populacao

ibge_dataset[~ibge_dataset["populacao"].isna()].head(9)

,id_municipio,cor_raca,sexo,grupo_idade,alfabetizacao,populacao,nome_regiao
46183,4123501,Parda,Mulheres,15 a 19 anos,Alfabetizadas,256.0,Sul
46184,5205513,Branca,Mulheres,15 a 19 anos,Alfabetizadas,256.0,Centro-Oeste
46185,1502707,Preta,Homens,15 a 19 anos,Alfabetizadas,256.0,Norte
46186,2703601,Parda,Homens,15 a 19 anos,Alfabetizadas,256.0,Nordeste
46187,2707305,Branca,Mulheres,15 a 19 anos,Alfabetizadas,256.0,Nordeste
46188,3551108,Branca,Mulheres,15 a 19 anos,Alfabetizadas,256.0,Sudeste
46189,1700707,Parda,Homens,15 a 19 anos,Alfabetizadas,256.0,Norte
46190,2307403,Branca,Mulheres,15 a 19 anos,Alfabetizadas,256.0,Nordeste
46191,5218904,Branca,Homens,15 a 19 anos,Alfabetizadas,256.0,Centro-Oeste